apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: auth
build:
  artifacts:
    - image: authorizer
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: 'src/**/*'
            dest: '.'
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml
      - k8s/upstream.yaml
